<?php

namespace HiEvents\Services\Infrastructure\Authorization;

use HiEvents\DomainObjects\Enums\Permission;

final class RoutePermissionRegistry
{
    private const ACTION = 'HiEvents\\Http\\Actions\\';

    public static function permissionForAction(?string $actionClass): ?Permission
    {
        return match ($actionClass) {
            self::ACTION . 'Auth\\LogoutAction',
            self::ACTION . 'Auth\\RefreshTokenAction',
            self::ACTION . 'Users\\GetMeAction',
            self::ACTION . 'Users\\UpdateMeAction',
            self::ACTION . 'Users\\ConfirmEmailChangeAction',
            self::ACTION . 'Users\\CancelEmailChangeAction',
            self::ACTION . 'Users\\ConfirmEmailAddressAction',
            self::ACTION . 'Users\\ResendEmailConfirmationAction',
            self::ACTION . 'Users\\ConfirmEmailWithCodeAction',
            self::ACTION . 'EmailTemplates\\GetDefaultEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\GetAvailableTokensAction' => Permission::AUTHENTICATED,

            self::ACTION . 'Admin\\Stats\\GetAdminStatsAction',
            self::ACTION . 'Admin\\Stats\\GetAdminDashboardDataAction',
            self::ACTION . 'Admin\\Attribution\\GetUtmAttributionStatsAction',
            self::ACTION . 'Admin\\Accounts\\GetAllAccountsAction',
            self::ACTION . 'Admin\\Accounts\\GetAccountAction',
            self::ACTION . 'Admin\\Accounts\\UpdateAccountVatSettingAction',
            self::ACTION . 'Admin\\Accounts\\AssignConfigurationAction',
            self::ACTION . 'Admin\\Configurations\\GetAllConfigurationsAction',
            self::ACTION . 'Admin\\Configurations\\CreateConfigurationAction',
            self::ACTION . 'Admin\\Configurations\\UpdateConfigurationAction',
            self::ACTION . 'Admin\\Configurations\\DeleteConfigurationAction',
            self::ACTION . 'Admin\\Users\\GetAllUsersAction',
            self::ACTION . 'Admin\\Events\\GetAllEventsAction',
            self::ACTION . 'Admin\\Events\\GetUpcomingEventsAction',
            self::ACTION . 'Admin\\Orders\\GetAllOrdersAction',
            self::ACTION . 'Admin\\Users\\StartImpersonationAction',
            self::ACTION . 'Admin\\Users\\StopImpersonationAction',
            self::ACTION . 'Admin\\FailedJobs\\GetAllFailedJobsAction',
            self::ACTION . 'Admin\\FailedJobs\\DeleteFailedJobAction',
            self::ACTION . 'Admin\\FailedJobs\\DeleteAllFailedJobsAction',
            self::ACTION . 'Admin\\FailedJobs\\RetryFailedJobAction',
            self::ACTION . 'Admin\\FailedJobs\\RetryAllFailedJobsAction',
            self::ACTION . 'Admin\\Messages\\GetAllMessagesAction',
            self::ACTION . 'Admin\\Messages\\ApproveMessageAction',
            self::ACTION . 'Admin\\GetMessagingTiersAction',
            self::ACTION . 'Admin\\Accounts\\UpdateAccountMessagingTierAction',
            self::ACTION . 'Admin\\GetSystemInfoAction' => Permission::SYSTEM_ADMIN,

            self::ACTION . 'Users\\CreateUserAction',
            self::ACTION . 'Users\\GetUsersAction',
            self::ACTION . 'Users\\GetUserAction',
            self::ACTION . 'Users\\UpdateUserAction',
            self::ACTION . 'Users\\ResendInvitationAction',
            self::ACTION . 'Users\\DeleteInvitationAction' => Permission::TEAM_MANAGE,

            self::ACTION . 'Accounts\\GetAccountAction' => Permission::ACCOUNT_VIEW,

            self::ACTION . 'Accounts\\UpdateAccountAction' => Permission::ACCOUNT_MANAGE,

            self::ACTION . 'Accounts\\Stripe\\GetStripeConnectAccountsAction',
            self::ACTION . 'Accounts\\Stripe\\CreateStripeConnectAccountAction',
            self::ACTION . 'Accounts\\Vat\\GetAccountVatSettingAction',
            self::ACTION . 'Accounts\\Vat\\UpsertAccountVatSettingAction',
            self::ACTION . 'TaxesAndFees\\CreateTaxOrFeeAction',
            self::ACTION . 'TaxesAndFees\\GetTaxOrFeeAction',
            self::ACTION . 'TaxesAndFees\\EditTaxOrFeeAction',
            self::ACTION . 'TaxesAndFees\\DeleteTaxOrFeeAction' => Permission::BILLING_MANAGE,

            self::ACTION . 'Organizers\\GetOrganizersAction',
            self::ACTION . 'Organizers\\GetOrganizerAction',
            self::ACTION . 'Organizers\\GetOrganizerEventsAction' => Permission::ORGANIZER_VIEW,

            self::ACTION . 'Organizers\\CreateOrganizerAction',
            self::ACTION . 'Organizers\\EditOrganizerAction',
            self::ACTION . 'Organizers\\UpdateOrganizerStatusAction',
            self::ACTION . 'Organizers\\DeleteOrganizerAction',
            self::ACTION . 'Organizers\\GetOrganizerDeletionStatusAction',
            self::ACTION . 'Organizers\\Settings\\GetOrganizerSettingsAction',
            self::ACTION . 'Organizers\\Settings\\PartialUpdateOrganizerSettingsAction' => Permission::ORGANIZER_MANAGE,

            self::ACTION . 'Organizers\\Stats\\GetOrganizerStatsAction',
            self::ACTION . 'Events\\Stats\\GetEventStatsAction',
            self::ACTION . 'Reports\\GetReportAction',
            self::ACTION . 'Reports\\GetOrganizerReportAction',
            self::ACTION . 'Financial\\GetFinancialReportAction' => Permission::REPORTS_VIEW,

            self::ACTION . 'Reports\\ExportOrganizerReportAction',
            self::ACTION . 'Financial\\ExportFinancialReportAction',
            self::ACTION . 'Questions\\ExportQuestionAnswersAction',
            self::ACTION . 'Attendees\\ExportAttendeesAction',
            self::ACTION . 'Orders\\ExportOrdersAction',
            self::ACTION . 'Affiliates\\ExportAffiliatesAction' => Permission::REPORTS_EXPORT,

            self::ACTION . 'Organizers\\Orders\\GetOrganizerOrdersAction',
            self::ACTION . 'Orders\\GetOrdersAction',
            self::ACTION . 'Orders\\GetOrderAction',
            self::ACTION . 'Orders\\DownloadOrderInvoiceAction',
            self::ACTION . 'Waitlist\\Organizer\\GetWaitlistEntriesAction',
            self::ACTION . 'Waitlist\\Organizer\\GetWaitlistStatsAction' => Permission::ORDERS_VIEW,

            self::ACTION . 'Orders\\EditOrderAction',
            self::ACTION . 'Orders\\MessageOrderAction',
            self::ACTION . 'Orders\\ResendOrderConfirmationAction',
            self::ACTION . 'Orders\\CancelOrderAction',
            self::ACTION . 'Orders\\MarkOrderAsPaidAction',
            self::ACTION . 'Waitlist\\Organizer\\OfferWaitlistEntryAction',
            self::ACTION . 'Waitlist\\Organizer\\CancelWaitlistEntryAction' => Permission::ORDERS_MANAGE,

            self::ACTION . 'Orders\\Payment\\RefundOrderAction' => Permission::ORDERS_REFUND,

            self::ACTION . 'Events\\GetEventsAction',
            self::ACTION . 'Events\\GetEventAction' => Permission::EVENT_VIEW,

            self::ACTION . 'Events\\CreateEventAction',
            self::ACTION . 'Events\\UpdateEventAction',
            self::ACTION . 'Events\\DeleteEventAction',
            self::ACTION . 'Events\\GetEventDeletionStatusAction',
            self::ACTION . 'Events\\DuplicateEventAction' => Permission::EVENT_MANAGE,

            self::ACTION . 'Events\\UpdateEventStatusAction' => Permission::EVENT_PUBLISH,

            self::ACTION . 'ProductCategories\\CreateProductCategoryAction',
            self::ACTION . 'ProductCategories\\EditProductCategoryAction',
            self::ACTION . 'ProductCategories\\DeleteProductCategoryAction',
            self::ACTION . 'Products\\CreateProductAction',
            self::ACTION . 'Products\\SortProductsAction',
            self::ACTION . 'Products\\EditProductAction',
            self::ACTION . 'Products\\DeleteProductAction',
            self::ACTION . 'EmailTemplates\\CreateOrganizerEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\UpdateOrganizerEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\DeleteOrganizerEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\CreateEventEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\UpdateEventEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\DeleteEventEmailTemplateAction',
            self::ACTION . 'Questions\\CreateQuestionAction',
            self::ACTION . 'Questions\\EditQuestionAction',
            self::ACTION . 'Questions\\DeleteQuestionAction',
            self::ACTION . 'Questions\\SortQuestionsAction',
            self::ACTION . 'Questions\\EditQuestionAnswerAction',
            self::ACTION . 'Events\\Images\\CreateEventImageAction',
            self::ACTION . 'Events\\Images\\DeleteEventImageAction',
            self::ACTION . 'PromoCodes\\CreatePromoCodeAction',
            self::ACTION . 'PromoCodes\\UpdatePromoCodeAction',
            self::ACTION . 'PromoCodes\\DeletePromoCodeAction',
            self::ACTION . 'Affiliates\\CreateAffiliateAction',
            self::ACTION . 'Affiliates\\UpdateAffiliateAction',
            self::ACTION . 'Affiliates\\DeleteAffiliateAction',
            self::ACTION . 'EventSettings\\EditEventSettingsAction',
            self::ACTION . 'EventSettings\\PartialEditEventSettingsAction',
            self::ACTION . 'CapacityAssignments\\CreateCapacityAssignmentAction',
            self::ACTION . 'CapacityAssignments\\UpdateCapacityAssignmentAction',
            self::ACTION . 'CapacityAssignments\\DeleteCapacityAssignmentAction',
            self::ACTION . 'CheckInLists\\CreateCheckInListAction',
            self::ACTION . 'CheckInLists\\UpdateCheckInListAction',
            self::ACTION . 'CheckInLists\\DeleteCheckInListAction',
            self::ACTION . 'Images\\CreateImageAction',
            self::ACTION . 'Images\\DeleteImageAction' => Permission::EVENT_CONTENT_MANAGE,

            self::ACTION . 'ProductCategories\\GetProductCategoriesAction',
            self::ACTION . 'ProductCategories\\GetProductCategoryAction',
            self::ACTION . 'Products\\GetProductAction',
            self::ACTION . 'Products\\GetProductsAction',
            self::ACTION . 'EmailTemplates\\GetOrganizerEmailTemplatesAction',
            self::ACTION . 'EmailTemplates\\PreviewOrganizerEmailTemplateAction',
            self::ACTION . 'EmailTemplates\\GetEventEmailTemplatesAction',
            self::ACTION . 'EmailTemplates\\PreviewEventEmailTemplateAction',
            self::ACTION . 'Questions\\GetQuestionAction',
            self::ACTION . 'Questions\\GetQuestionsAction',
            self::ACTION . 'Events\\Images\\GetEventImagesAction',
            self::ACTION . 'PromoCodes\\GetPromoCodesAction',
            self::ACTION . 'PromoCodes\\GetPromoCodeAction',
            self::ACTION . 'Affiliates\\GetAffiliatesAction',
            self::ACTION . 'Affiliates\\GetAffiliateAction',
            self::ACTION . 'EventSettings\\GetEventSettingsAction',
            self::ACTION . 'EventSettings\\GetPlatformFeePreviewAction',
            self::ACTION . 'CapacityAssignments\\GetCapacityAssignmentsAction',
            self::ACTION . 'CapacityAssignments\\GetCapacityAssignmentAction' => Permission::EVENT_CONTENT_VIEW,

            self::ACTION . 'Attendees\\GetAttendeesAction',
            self::ACTION . 'Attendees\\GetAttendeeAction' => Permission::ATTENDEES_VIEW,

            self::ACTION . 'Attendees\\CreateAttendeeAction',
            self::ACTION . 'Attendees\\EditAttendeeAction',
            self::ACTION . 'Attendees\\PartialEditAttendeeAction',
            self::ACTION . 'Attendees\\ResendAttendeeTicketAction' => Permission::ATTENDEES_MANAGE,

            self::ACTION . 'Attendees\\CheckInAttendeeAction',
            self::ACTION . 'CheckInLists\\GetCheckInListsAction',
            self::ACTION . 'CheckInLists\\GetCheckInListAction' => Permission::CHECK_IN_MANAGE,

            self::ACTION . 'Messages\\SendMessageAction',
            self::ACTION . 'Messages\\GetMessagesAction',
            self::ACTION . 'Messages\\CancelMessageAction',
            self::ACTION . 'Messages\\GetMessageRecipientsAction' => Permission::MESSAGES_MANAGE,

            self::ACTION . 'Organizers\\Webhooks\\CreateOrganizerWebhookAction',
            self::ACTION . 'Organizers\\Webhooks\\GetOrganizerWebhooksAction',
            self::ACTION . 'Organizers\\Webhooks\\EditOrganizerWebhookAction',
            self::ACTION . 'Organizers\\Webhooks\\GetOrganizerWebhookAction',
            self::ACTION . 'Organizers\\Webhooks\\DeleteOrganizerWebhookAction',
            self::ACTION . 'Organizers\\Webhooks\\GetOrganizerWebhookLogsAction',
            self::ACTION . 'Webhooks\\CreateWebhookAction',
            self::ACTION . 'Webhooks\\GetWebhooksAction',
            self::ACTION . 'Webhooks\\EditWebhookAction',
            self::ACTION . 'Webhooks\\GetWebhookAction',
            self::ACTION . 'Webhooks\\DeleteWebhookAction',
            self::ACTION . 'Webhooks\\GetWebhookLogsAction' => Permission::INTEGRATIONS_MANAGE,

            default => null,
        };
    }
}
